### ISSUE TITLE
Please tell me why I can’t download it.

### ISSUE THREAD

**Issue by danny740211** [TAJLNsScripts/iq.com-Downloader-V2#3]
Please tell me why I can’t download it.
![image](https://github.com/TAJLNsScripts/iq.com-Downloader-V2/assets/29675187/5c6f417e-8c4f-44af-b82d-98ffdbb18ac6)

**Comment by irabro1992** [comment]
you need to put iq cookie correctly. it's work fine.

**Comment by danny740211** [comment]
Thank you, the test is now available for download
